# -*- coding: utf-8 -*-
"""pretrained data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10gCFeYBJlK_xBtmQHRwtI-p9P5oahWaw
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

import os
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
keras=tf.keras

import tensorflow_datasets as tfds
tfds.disable_progress_bar()
#split the data manaually 80%train, 10%test and 10%validation
(raw_train,raw_validation,raw_test),metadata=tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]','train[80%:90%]','train[90%:]'],
    with_info=True,
    as_supervised=True,
)